# Generated by Django 3.1.2 on 2022-01-12 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mseq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mprojects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msequences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msequences', to='mseq.project'),
        ),
    ]
