# Generated by Django 3.1.2 on 2022-02-24 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seqstat',
            old_name='rAmbiguous',
            new_name='r_Ambiguous',
        ),
        migrations.RemoveField(
            model_name='seqstat',
            name='rAvgLen',
        ),
        migrations.RemoveField(
            model_name='seqstat',
            name='rAvgQual',
        ),
        migrations.RemoveField(
            model_name='seqstat',
            name='rErrQual',
        ),
        migrations.RemoveField(
            model_name='seqstat',
            name='rGeeCee',
        ),
        migrations.RemoveField(
            model_name='seqstat',
            name='rMaxLen',
        ),
        migrations.RemoveField(
            model_name='seqstat',
            name='rMinLen',
        ),
        migrations.RemoveField(
            model_name='seqstat',
            name='rReads',
        ),
        migrations.RemoveField(
            model_name='seqstat',
            name='rYield',
        ),
        migrations.AddField(
            model_name='seqstat',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seqstats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seqstat',
            name='r_AvgLen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seqstat',
            name='r_AvgQual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seqstat',
            name='r_ErrQual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seqstat',
            name='r_GeeCee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seqstat',
            name='r_MaxLen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seqstat',
            name='r_MinLen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seqstat',
            name='r_Reads',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seqstat',
            name='r_Yield',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
