# Generated by Django 2.2.22 on 2021-08-11 18:38

import apps.isolate.gbase.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Virulome',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seqtype', models.CharField(max_length=100)),
                ('num_found', models.IntegerField()),
                ('virulome', djongo.models.fields.ArrayField(model_container=apps.isolate.gbase.models.GeneCoverage)),
                ('DateCreated', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('LastUpdate', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('Description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virulomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resistome',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seqtype', models.CharField(max_length=100)),
                ('num_found', models.IntegerField()),
                ('resistome', djongo.models.fields.ArrayField(model_container=apps.isolate.gbase.models.GeneCoverage)),
                ('DateCreated', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('LastUpdate', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('Description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resistomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mlst',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seqtype', models.CharField(max_length=100)),
                ('scheme', models.CharField(max_length=100)),
                ('st', models.IntegerField()),
                ('alleles', djongo.models.fields.ArrayField(model_container=apps.isolate.gbase.models.Allele)),
                ('DateCreated', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('LastUpdate', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('Description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mlsts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seqtype', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.IntegerField()),
                ('bp', models.IntegerField()),
                ('Ns', models.IntegerField()),
                ('gaps', models.IntegerField()),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('avg', models.IntegerField()),
                ('N50', models.IntegerField()),
                ('DateCreated', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('LastUpdate', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('Description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('seqtype', models.CharField(max_length=100)),
                ('DateCreated', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('LastUpdate', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('Description', models.TextField()),
                ('gff', djongo.models.fields.ArrayField(model_container=apps.isolate.gbase.models.Gff)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ganalyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
