# Generated by Django 2.2.22 on 2021-08-11 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('DateCreated', models.DateTimeField(auto_now=True, verbose_name='date created')),
                ('LastUpdate', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('pct_reads_mapped', models.FloatField()),
                ('num_reads_mapped', models.IntegerField()),
                ('main_lin', models.CharField(max_length=100, null=True)),
                ('sublin', models.CharField(max_length=100, null=True)),
                ('num_dr_variants', models.IntegerField()),
                ('num_other_variants', models.IntegerField()),
                ('drtype', models.CharField(max_length=50)),
                ('rifampicin', models.CharField(max_length=150)),
                ('isoniazid', models.CharField(max_length=150)),
                ('pyrazinamide', models.CharField(max_length=150)),
                ('ethambutol', models.CharField(max_length=150)),
                ('streptomycin', models.CharField(max_length=150)),
                ('fluoroquinolones', models.CharField(max_length=150)),
                ('moxifloxacin', models.CharField(max_length=150)),
                ('ofloxacin', models.CharField(max_length=150)),
                ('levofloxacin', models.CharField(max_length=150)),
                ('ciprofloxacin', models.CharField(max_length=150)),
                ('aminoglycosides', models.CharField(max_length=150)),
                ('amikacin', models.CharField(max_length=150)),
                ('kanamycin', models.CharField(max_length=150)),
                ('capreomycin', models.CharField(max_length=150)),
                ('ethionamide', models.CharField(max_length=150)),
                ('para_aminosalicylic_acid', models.CharField(max_length=150)),
                ('cycloserine', models.CharField(max_length=150)),
                ('linezolid', models.CharField(max_length=150)),
                ('bedaquiline', models.CharField(max_length=150)),
                ('clofazimine', models.CharField(max_length=150)),
                ('delamanid', models.CharField(max_length=150)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
