# Generated by Django 2.2.22 on 2021-07-29 17:44

import apps.isolate.tb.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('commit', models.CharField(max_length=50)),
                ('Merge', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('drug', models.CharField(max_length=100)),
                ('confidence', models.CharField(max_length=100)),
                ('literature', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lineage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lin', models.CharField(max_length=100)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('spoligotype', models.CharField(blank=True, max_length=100, null=True)),
                ('rd', models.CharField(blank=True, max_length=100, null=True)),
                ('frac', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapper', models.CharField(max_length=100)),
                ('variant_caller', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug', models.CharField(max_length=100)),
                ('mutations', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chr', models.CharField(max_length=100)),
                ('genome_pos', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('change', models.CharField(max_length=100)),
                ('freq', models.FloatField()),
                ('nucleotide_change', models.CharField(max_length=100)),
                ('locus_tag', models.CharField(max_length=100)),
                ('gene', models.CharField(max_length=100)),
                ('_internal_change', models.CharField(max_length=100)),
                ('variant_annotations', djongo.models.fields.EmbeddedField(model_container=apps.isolate.tb.models.VariantAnnotation, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VariantAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrVariant',
            fields=[
                ('variant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tb.Variant')),
                ('drugs', djongo.models.fields.ArrayField(model_container=apps.isolate.tb.models.Drug)),
            ],
            options={
                'abstract': False,
            },
            bases=('tb.variant',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('main_lin', models.CharField(max_length=100, null=True)),
                ('sublin', models.CharField(max_length=100, null=True)),
                ('drtype', models.CharField(max_length=50)),
                ('num_dr_variants', models.IntegerField()),
                ('num_other_variants', models.IntegerField()),
                ('pct_reads_mapped', models.FloatField()),
                ('num_reads_mapped', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=5000, null=True)),
                ('lineage', djongo.models.fields.ArrayField(model_container=apps.isolate.tb.models.Lineage)),
                ('dr_resistances', djongo.models.fields.ArrayField(model_container=apps.isolate.tb.models.Resistance)),
                ('dr_variants', djongo.models.fields.ArrayField(model_container=apps.isolate.tb.models.DrVariant)),
                ('other_variants', djongo.models.fields.ArrayField(model_container=apps.isolate.tb.models.Variant)),
                ('db_version', djongo.models.fields.EmbeddedField(model_container=apps.isolate.tb.models.DB_version, null=True)),
                ('pipeline', djongo.models.fields.EmbeddedField(model_container=apps.isolate.tb.models.Pipeline, null=True)),
                ('tbprofiler_version', models.CharField(max_length=100)),
                ('timestamp', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
